version: '3.8'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
    - ./ssl:/usr/share/elasticsearch/config/certs
    - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
        memlock:
          soft: -1
          hard: -1
    environment:
      #discovery.type: single-node
      cluster.name: elk-cluster
      node.name: elasticsearch
      network.host: "0.0.0.0"
      ES_JAVA_OPTS: "-Xmx4G -Xms4G"
      ELASTIC_PASSWORD: elastic-admin
      ELASTIC_USERNAME: elastic
      NODE_DATA: "true"
      NODE_INGEST: "true"
      NODE_MASTER: "true"
      DISCOVERY_SEED_HOSTS: elasticsearch
      cluster.initial_master_nodes: elasticsearch
    networks:
      - elk-docker

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.0
    container_name: logstash
    volumes:
    - ./logstash.yml:/usr/share/logstash/config/logstash.yml
    - ./pipelines.yml:/usr/share/logstash/config/pipelines.yml
    - ./logstash-pipelines.yml:/usr/share/logstash/pipeline/logstash-pipelines.yml
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTICSEARCH_PASSWORD: elastic-admin
      ELASTICSEARCH_USERNAME: elastic
    networks:
      - elk-docker
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.14.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      ELASTICSEARCH_PASSWORD: elastic-admin
      ELASTICSEARCH_USERNAME: elastic
      SERVER_HOST: "0.0.0.0"
    networks:
      - elk-docker
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.14.0
    volumes:
    - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - elk-docker
    depends_on:
      - logstash

networks:
  elk-docker:
    driver: bridge

volumes:
  elasticsearch-data:
  logstash-data: